# Build steps common to all platforms

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: custom
    customCommand: i -g npm
  displayName: 'Update npm'
  condition: eq(variables['node_version'], '6.x')

- task: Npm@1
  inputs:
    command: custom
    customCommand: ci
  displayName: 'Install dependencies'

- bash: |
    npm test -- -- --reporter mocha-junit-reporter --reporter-options mochaFile=./test-results.xml
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: $(os_name) Node $(node_version)
  displayName: 'Publishing the test results'
  condition: always()

- bash: |
    export DISPLAY=$(DISPLAY)
    npm run mocha-browser-test
  displayName: 'Run Firefox tests'
  condition: |
    and(
      variables.run_browser_tests,
      in(variables['os_name'], 'Linux', 'Windows')
    )

- bash: npm run mocha-browser-test -- --browsers Safari
  displayName: 'Run Safari tests'
  condition: |
    and(
      variables.run_browser_tests,
      in(variables['os_name'], 'OSX')
    )

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/browser-test-results.xml'
    testRunTitle: $(os_name) Node $(node_version) Browser tests
  displayName: 'Publishing the browser test results'
  condition: variables.run_browser_tests

- bash: |
    export COVERALLS_REPO_TOKEN=$(COVERALLS_REPO_TOKEN)
    npm run coveralls
  displayName: 'Run coveralls'
  condition: variables.run_coveralls
